################################################################################
# Load necessary libraries
library(tidyverse)
library(VennDiagram)
library(gridExtra)
library(grid)

################################################################################
# Function to create and save a Venn diagram
create_venn_diagram <- function(path, file1, file2, suffix) {
  # Construct file paths
  file1_path <- paste0(path, "/DE_", file1, suffix)
  file2_path <- paste0(path, "/DE_", file2, suffix)
  
  # Import the DE gene CSV files
  de_genes_file1 <- read.csv(file1_path, row.names = 1)
  de_genes_file_2 <- read.csv(file2_path, row.names = 1)
  
  # Extract gene names (assuming row names are gene names)
  genes_trt <- rownames(de_genes_file1)
  genes_mock <- rownames(de_genes_file_2)
  
  # Create a list of gene sets
  gene_list <- list(Treatment = genes_trt, Mock = genes_mock)
  
  # Create the Venn diagram
  venn.plot <- venn.diagram(
    x = gene_list,
    category.names = c(file1, file2),
    filename = NULL, # We will save it using grid.newpage and grid.draw
    output = TRUE,
    imagetype = "png",
    height = 3000,
    width = 3000,
    resolution = 300,
    compression = "lzw",
    lwd = 2,
    col = c("red", "blue"),
    fill = c(alpha("red", 0.5), alpha("blue", 0.5)),
    cex = 1.2,
    fontface = "bold",
    fontfamily = "sans",
    cat.cex = 1.2,
    cat.fontface = "bold",
    cat.fontfamily = "sans",
    cat.pos = c(-15, 25), # Adjust the positions of category names
    cat.dist = c(0.02, 0.03),
    cat.default.pos = "outer",
    cat.col = c("red", "blue")
  )
  
  output_file <- paste0(path, "/", file1, "-", file2, "_venn_diagram.png")
  
  # Save the Venn diagram using grid
  png(output_file, width = 6, height = 6, units = "in", res = 300)
  grid.newpage()
  grid.draw(venn.plot)
  dev.off()
}

# Function to create Venn diagram with forced_position
create_venn_diagram_forced_position <- function(path, file1, file2, suffix) {
  
  # Construct file paths
  file1_path <- paste0(path, "/DE_", file1, suffix)
  file2_path <- paste0(path, "/DE_", file2, suffix)
  
  # Import the DE gene CSV files
  file_1 <- read.csv(file1_path, row.names = 1)
  file_2 <- read.csv(file2_path, row.names = 1)
  
  # Extract gene names (assuming row names are gene names)
  genes_trt <- rownames(file_1)
  genes_mock <- rownames(file_2)
  
  # Create a list of gene sets
  gene_list <- list(Mock = genes_mock, Treatment = genes_trt)
  
  # Create the Venn diagram
  venn.plot <- venn.diagram(
    x = gene_list,
    category.names = c(file2, file1), # Ensure the smaller category (file1) is on the right
    filename = NULL, # We will save it using grid.newpage and grid.draw
    output = TRUE,
    imagetype = "png",
    height = 3000,
    width = 3000,
    resolution = 300,
    compression = "lzw",
    lwd = 2,
    col = c("blue", "red"), # Ensure the correct colors for each category
    fill = c(alpha("blue", 0.5), alpha("red", 0.5)), # Ensure the correct fill colors
    cex = 1.2,
    fontface = "bold",
    fontfamily = "sans",
    cat.cex = 1.2,
    cat.fontface = "bold",
    cat.fontfamily = "sans",
    cat.pos = c(15, -25), # Adjust the positions of category names
    cat.dist = c(0.02, 0.03),
    cat.default.pos = "outer",
    cat.col = c("blue", "red"),
    rotation.degree = 180, # Rotate the diagram
    force.overlap = TRUE # Force overlap to manually adjust the layout
  )
  
  output_file <- paste0(path, "/", file1, "-", file2, "_venn_diagram_forced_position.png")
  
  # Save the Venn diagram using grid
  png(output_file, width = 6, height = 6, units = "in", res = 300)
  grid.newpage()
  grid.draw(venn.plot)
  dev.off()
}
################################################################################
fileName_suffix <- "_padj-0.05_log2foldChange-1.csv"

# Create venn diagrams

# Res vs Sus
create_venn_diagram("BLS_DE_Results/01_Res-vs-Sus/With_log2FC_threshold", "U17BI1_vs_U89BI1", "U17BM1_vs_U89BM1", fileName_suffix)
create_venn_diagram("BLS_DE_Results/01_Res-vs-Sus/With_log2FC_threshold", "U17BI3_vs_U89BI3", "U17BM3_vs_U89BM3", fileName_suffix)

create_venn_diagram("BLS_DE_Results/01_Res-vs-Sus/With_log2FC_threshold", "U17BI1_vs_U89BI1", "U17BI3_vs_U89BI3", fileName_suffix)

# Trt vs Mock
create_venn_diagram("BLS_DE_Results/02_Trt-vs-Mock/With_log2FC_threshold", "U17BI1_vs_U17BM1", "U89BI1_vs_U89BM1", fileName_suffix)

## below two lines are for same, but to be consistent I rotate the plot with forced position
#(and used the plot in figures generated by second line)
create_venn_diagram("BLS_DE_Results/02_Trt-vs-Mock/With_log2FC_threshold", "U17BI3_vs_U17BM3", "U89BI3_vs_U89BM3", fileName_suffix)
create_venn_diagram_forced_position("BLS_DE_Results/02_Trt-vs-Mock/With_log2FC_threshold", "U17BI3_vs_U17BM3", "U89BI3_vs_U89BM3", fileName_suffix)

create_venn_diagram("BLS_DE_Results/02_Trt-vs-Mock/With_log2FC_threshold", "U17BI1_vs_U17BM1", "U89BI3_vs_U89BM3", fileName_suffix)

# Time 1d vs 3d
create_venn_diagram("BLS_DE_Results/03_Time1d-vs-3d/With_log2FC_threshold", "U17BI1_vs_U17BI3", "U17BM1_vs_U17BM3", fileName_suffix)
create_venn_diagram("BLS_DE_Results/03_Time1d-vs-3d/With_log2FC_threshold", "U17BI1_vs_U17BI3", "U89BI1_vs_U89BI3", fileName_suffix)
create_venn_diagram("BLS_DE_Results/03_Time1d-vs-3d/With_log2FC_threshold", "U89BI1_vs_U89BI3", "U17BM1_vs_U17BM3", fileName_suffix)
create_venn_diagram("BLS_DE_Results/03_Time1d-vs-3d/With_log2FC_threshold", "U17BM1_vs_U17BM3", "U89BI1_vs_U89BI3", fileName_suffix)
################################################################################
